spring:
  profiles:
    active: test
  mail:
    host: smtp.gmail.com
    port: 587
    username: kmk930833@gmail.com
    password: qrxkuukjrawvagnf
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/limu
    username: maeng0830
    password: '!@aud221166'

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true


---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa

  sql:
    init:
      mode: embedded
      data-locations: classpath:dataH2.sql

